-------------------------------------------------
--Calculate win rate for FY23 by Rep Segment and FQ
--------------------------------------------------

--CTE to dedupe opps and provide opp level details
WITH Closed_Deals AS(
    SELECT 
    OPPORTUNITY_ID,
    OPPORTUNITY_NAME, 
    CONCAT(OPPORTUNITY_CLOSE_DATE_FISCAL_YEAR,'-',OPPORTUNITY_CLOSE_DATE_FISCAL_QUARTER_NAME) as FQ_Close,
    OPPORTUNITY_OWNER_NAME, 
    OPPORTUNITY_OWNER_ROLE,
    OPPORTUNITY_STAGENAME,
    CASE WHEN OPPORTUNITY_OWNER_SEGMENT = 'N/A' THEN 'New Markets'
    ELSE OPPORTUNITY_OWNER_SEGMENT END as Rep_Segment,
    ROUND(SUM(MERCHANT_OPPORTUNITY_EST_GMV_FY23)) as MERCHANT_OPPORTUNITY_EST_GMV_FY23,
    ROUND(SUM(MERCHANT_OPPORTUNITY_EST_GMV_RAW)) as MERCHANT_OPPORTUNITY_EST_GMV_RAW    
    FROM PROD__US.DBT_ANALYTICS.SALES_TERRITORY_DEAL_MART
    WHERE IS_SALES_OPPORTUNITY = TRUE AND OPPORTUNITY_CLOSE_DATE_FISCAL_YEAR = 2023 AND IS_OPPORTUNITY_CLOSED = TRUE
    GROUP BY 1,2,3,4,5,6,7
)

--Calc Win Rates
SELECT 
Rep_Segment, 
FQ_Close, 
COUNT(OPPORTUNITY_ID) as Total_Closed,
SUM(CASE WHEN OPPORTUNITY_STAGENAME IN ('7.Closed Won') THEN 1 ELSE 0 END) as Won,
SUM(CASE WHEN OPPORTUNITY_STAGENAME IN ('8.Closed Lost') THEN 1 ELSE 0 END) as Lost,
ROUND(Won/(Won + Lost),2) as Win_Rate,
SUM(CASE WHEN OPPORTUNITY_STAGENAME IN ('7.Closed Won') THEN MERCHANT_OPPORTUNITY_EST_GMV_FY23 ELSE 0 END) as Won_Est_GMV,
SUM(CASE WHEN OPPORTUNITY_STAGENAME IN ('8.Closed Lost') THEN MERCHANT_OPPORTUNITY_EST_GMV_FY23 ELSE 0 END) as Lost_Est_GMV,
ROUND(Won_Est_GMV/(Won_Est_GMV + Lost_Est_GMV),2) as Win_Rate_Est_GMV
FROM Closed_Deals
GROUP BY 1,2
ORDER BY 2,1

--View opp level data from CTE
--SELECT * FROM Closed_Deals

