--Identify FY22 deals created,and closed (won or lost) at the same point into FY as we are currently (8/30/22)
SELECT s.SNAPSHOT_DATE
,s.ACCOUNT_NAME
,s.OPPORTUNITY_NAME
,s.STAGE
,s.CREATEDDATE
,s.FISCAL_PERIOD
,s.CLOSEDATE
,CASE WHEN FISCAL_PERIOD IN ('Q1-2022','Q2-2022','Q3-2022','Q4-2022') AND SEGMENT_MAPPING IN ('Enterprise','Key') THEN s.ESTIMATED_GMV*.45
      ELSE s.ESTIMATED_GMV END as Est_GMV
,CASE WHEN FISCAL_PERIOD IN ('Q1-2022','Q2-2022','Q3-2022','Q4-2022') AND SEGMENT_MAPPING IN ('Enterprise','Key') THEN s.FORECASTED_EST_GMV*.45
      ELSE s.FORECASTED_EST_GMV END as Forecasted_Est_GMV
,s.FORECASTED_PROBABILLITY
,s.FORECASTED_TAS
,s.ESTIMATED_REVENUE_SIGNED
,s.FORECASTED_ESTIMATED_REVENUE
,CASE WHEN s.SEGMENT_MAPPING IN ('Strategic Brands') THEN 'Enterprise' 
      WHEN s.SEGMENT_MAPPING IN ('Mid-Market', 'Other') THEN 'SMB'
      WHEN s.SEGMENT_MAPPING IS NULL THEN 'SMB'
      ELSE s.SEGMENT_MAPPING END as SEGMENT_MAPPING
,s.VERTICAL_MAPPING
,CASE WHEN STAT='Forecast' THEN FORECAST_CATEGORY
ELSE STAT END as FORECAST_STAGE
,v.MERCHANT_ARI
,v.OPPORTUNITY_LAUNCH_DATE as Integrate_Date --Integrate Date
,v.V_LAUNCH_DATE as Capture_Date --Capture Date
FROM PROD__WORKSPACE__US.SCRATCH_T_REVENUEOPS.V_SFDC_SALES_FORECAST s
LEFT JOIN PROD__WORKSPACE__US.SCRATCH_T_REVENUEOPS.V_SALES_OPP_REV_GMV_PERFORMANCE v
ON s.OPPORTUNITY_ID= v.OPPORTUNITY_ID
WHERE FISCAL_PERIOD IN ( 'Q1-2022','Q2-2022','Q3-2022','Q4-2022')
AND s.CREATEDDATE >= '2021-08-30' AND s.CLOSEDATE < '2022-07-01'
