--Pipeline generation cohorts
SELECT s.SNAPSHOT_DATE
,s.ACCOUNT_NAME
,s.OPPORTUNITY_NAME
,s.STAGE
,s.CREATEDDATE
,s.FISCAL_PERIOD
,s.CLOSEDATE
,CASE WHEN SEGMENT_MAPPING IN ('Enterprise','Key') THEN s.ESTIMATED_GMV*.45
      ELSE s.ESTIMATED_GMV END as Est_GMV
,CASE WHEN SEGMENT_MAPPING IN ('Enterprise','Key') THEN s.FORECASTED_EST_GMV*.45
      ELSE s.FORECASTED_EST_GMV END as Forecasted_Est_GMV
,s.FORECASTED_PROBABILLITY
,s.FORECASTED_TAS
,s.ESTIMATED_REVENUE_SIGNED
,s.FORECASTED_ESTIMATED_REVENUE
,CASE WHEN s.SEGMENT_MAPPING IN ('Strategic Brands') THEN 'Enterprise' 
      WHEN s.SEGMENT_MAPPING IN ('Mid-Market', 'Other') THEN 'SMB'
      WHEN s.SEGMENT_MAPPING IS NULL THEN 'SMB'
      ELSE s.SEGMENT_MAPPING END as SEGMENT_MAPPING
,s.VERTICAL_MAPPING
,CASE WHEN STAT='Forecast' THEN FORECAST_CATEGORY
ELSE STAT END as FORECAST_STAGE
,v.MERCHANT_ARI
,v.OPPORTUNITY_LAUNCH_DATE as Integrate_Date --Integrate Date
,v.V_LAUNCH_DATE as Capture_Date --Capture Date
,CASE WHEN s.CREATEDDATE >= '2020-07-01' AND s.CREATEDDATE < '2020-10-01' THEN 'FY21-Q1'
      WHEN s.CREATEDDATE >= '2020-10-01' AND s.CREATEDDATE < '2021-01-01' THEN 'FY21-Q2'
      WHEN s.CREATEDDATE >= '2021-01-01' AND s.CREATEDDATE < '2021-04-01' THEN 'FY21-Q3'
      WHEN s.CREATEDDATE >= '2021-04-01' AND s.CREATEDDATE < '2021-07-01' THEN 'FY21-Q4'
      WHEN s.CREATEDDATE >= '2021-07-01' AND s.CREATEDDATE < '2021-10-01' THEN 'FY22-Q1'
      WHEN s.CREATEDDATE >= '2021-10-01' AND s.CREATEDDATE < '2022-01-01' THEN 'FY22-Q2'
      WHEN s.CREATEDDATE >= '2022-01-01' AND s.CREATEDDATE < '2022-04-01' THEN 'FY22-Q3'
      WHEN s.CREATEDDATE >= '2022-04-01' AND s.CREATEDDATE < '2022-07-01' THEN 'FY22-Q4'
      ELSE 'ERROR' END as Cohort_CreateDate
FROM PROD__WORKSPACE__US.SCRATCH_T_REVENUEOPS.V_SFDC_SALES_FORECAST s
LEFT JOIN PROD__WORKSPACE__US.SCRATCH_T_REVENUEOPS.V_SALES_OPP_REV_GMV_PERFORMANCE v
ON s.OPPORTUNITY_ID= v.OPPORTUNITY_ID
WHERE s.CREATEDDATE >= '2020-07-01' AND s.CREATEDDATE < '2022-07-01'
ORDER BY s.CREATEDDATE asc
